spring:
  data:
    mongodb:
      username: user
      password: pwd
      host: localhost
      port: 0
      database: test-db
      authentication-database: admin
      auto-index-creation: true


de:
  flapdoodle:
    mongodb:
      embedded:
        version: 5.0.5


---


spring.data.mongodb.host: mongodb
spring.data.mongodb.port: 27017


spring:
  datasource:
    url: jdbc:mysql://mysql1/test-db
    username: user
    password: pwd

  jpa:
    hibernate:
      ddl-auto: none

  config:
    activate:
      on-profile: docker

  sql:
    init:
      platform: mysql
      mode: always




server.port: 8080

spring.datasource.hikari.initializationFailTimeout: 60000